//
//  SeeNoteInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SeeNoteInteractor: SeeNoteInteractorInputProtocol {

    weak var presenter: SeeNoteInteractorOutputProtocol?
}
