//
//  SeeNoteViewController.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SeeNoteViewController: BaseViewController {

	var presenter: SeeNotePresenterProtocol?
    var idNote: String = "1"
    weak var deleagate: AddNoteDelegate?

    @IBOutlet weak var tvNote: UITextView!
    override func setUpViews() {
        super.setUpViews()
        self.presenter?.getViewNote(idNote: idNote)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
        
        addButtonImageToNavigation(image: #imageLiteral(resourceName: "edit"), style: .right, action: #selector(clickButtonRight))
    }
    @objc func clickButtonRight(){
        addButtonTextToNavigation(title: "Xong", style: .right, action: #selector(clickFinish),textColor: .black, font: AppFont.fontBold16)
        tvNote.isEditable = true
        tvNote.becomeFirstResponder()
    }
    
    @objc func clickFinish(){
        let description = tvNote.text ?? ""
        if description != "" {
            self.presenter?.editNote(idNote: self.presenter?.getIdNote() ?? "", description: description)
            tvNote.isEditable = false
            tvNote.resignFirstResponder()
            addButtonImageToNavigation(image: #imageLiteral(resourceName: "edit"), style: .right, action: #selector(clickButtonRight))
        }
    }

}
extension SeeNoteViewController : SeeNoteViewProtocol{
    func reloadView() {
        let title = self.presenter?.getTitleNote() ?? ""
        let description = self.presenter?.getDescriptionNote() ?? ""
        setTitleNavigation(title: title)
        tvNote.text = description
    }
    
    func editNoteSuccessed() {
        deleagate?.addNoteSuccessed()
        self.pop(animated: true)
    }
}
