//
//  ResultCompetitionRouter.swift
//  EnglishApp
//
//  Created vinova on 5/23/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ResultCompetitionRouter: ResultCompetitionWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ResultCompetitionViewController.initFromNib()
        let interactor = ResultCompetitionInteractor()
        let router = ResultCompetitionRouter()
        let presenter = ResultCompetitionPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
