//
//  ResultCompetitionInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/23/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ResultCompetitionInteractor: ResultCompetitionInteractorInputProtocol {

    weak var presenter: ResultCompetitionInteractorOutputProtocol?
}
