//
//  ResultCompetitionViewController.swift
//  EnglishApp
//
//  Created vinova on 5/23/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class ResultCompetitionViewController: ListManagerVC {

	var presenter: ResultCompetitionPresenterProtocol?
    
    @IBOutlet weak var tbvResultCompetition: UITableView!
    var idCompetition: String = ""
    
	override func viewDidLoad() {
        customTitle = LocalizableKey.result_team.showLanguage
        messageNoData = LocalizableKey.no_team_joined.showLanguage
        super.viewDidLoad()
//        self.tableView.contentInset = UIEdgeInsets(top: 20, left: 0, bottom: 0, right: 0)
    }
    
    override func registerTableView() {
        super.registerTableView()
        tableView.registerXibFile(CellResultCompetition.self)
    }
    
    override func callAPI() {
        super.callAPI()
        self.presenter?.getResultTeam(idCompetition: idCompetition, offset: self.offset)
    }
    
    override func cellForRowListManager(item: Any, _ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let data = item as! CompetitionResultTeamEntity
        let cell = tableView.dequeue(CellResultCompetition.self, for: indexPath)
        cell.setupData(dataCell: data)
        return cell
    }
}

extension ResultCompetitionViewController : ResultCompetitionViewProtocol{
    func reloadView(respone: [CompetitionResultTeamEntity]) {
        initLoadData(data: respone)
    }
}

extension ResultCompetitionViewController: IndicatorInfoProvider{
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.result_team.showLanguage)
    }
}
