//
//  CompetitionPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/13/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CompetitionPresenter: CompetitionPresenterProtocol, CompetitionInteractorOutputProtocol {

    weak private var view: CompetitionViewProtocol?
    var interactor: CompetitionInteractorInputProtocol?
    private let router: CompetitionWireframeProtocol

    init(interface: CompetitionViewProtocol, interactor: CompetitionInteractorInputProtocol?, router: CompetitionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
