//
//  HistoryBeeInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/19/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryBeeInteractor: HistoryBeeInteractorInputProtocol {

    weak var presenter: HistoryBeeInteractorOutputProtocol?
}
