//
//  HistoryBeeRouter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/19/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryBeeRouter: HistoryBeeWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(wallet_type: Int) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = HistoryBeeViewController(nibName: nil, bundle: nil)
        view.wallet_type = wallet_type
        let interactor = HistoryBeeInteractor()
        let router = HistoryBeeRouter()
        let presenter = HistoryBeePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
