//
//  CreateExerciseProtocols.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CreateExerciseWireframeProtocol: class {

}
//MARK: Presenter -
protocol CreateExercisePresenterProtocol: class {

    var interactor: CreateExerciseInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol CreateExerciseInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol CreateExerciseInteractorInputProtocol: class {

    var presenter: CreateExerciseInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol CreateExerciseViewProtocol: class {

    var presenter: CreateExercisePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
