//
//  CreateExercisePresenter.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CreateExercisePresenter: CreateExercisePresenterProtocol, CreateExerciseInteractorOutputProtocol {

    weak private var view: CreateExerciseViewProtocol?
    var interactor: CreateExerciseInteractorInputProtocol?
    private let router: CreateExerciseWireframeProtocol

    init(interface: CreateExerciseViewProtocol, interactor: CreateExerciseInteractorInputProtocol?, router: CreateExerciseWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
