//
//  CreateExerciseRouter.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CreateExerciseRouter: CreateExerciseWireframeProtocol {
  

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = CreateExerciseViewController.initFromNib()
        let interactor = CreateExerciseInteractor()
        let router = CreateExerciseRouter()
        let presenter = CreateExercisePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func gotoExercise(viewExerciseEntity: ViewExerciseEntity) {
        let vc = NameExerciseRouter.createModule(viewExerciseEntity: viewExerciseEntity)
        self.viewController?.push(controller: vc)
    }
    
    func gotoStore() {
        let vc = StudyPackDetailRouter.createModule(id: "-1")
        self.viewController?.push(controller: vc)
    }
}
