//
//  CreateExerciseProtocols.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CreateExerciseWireframeProtocol: class {
    func gotoExercise(viewExerciseEntity: ViewExerciseEntity)
    func gotoStore()
}
//MARK: Presenter -
protocol CreateExercisePresenterProtocol: class {

    var interactor: CreateExerciseInteractorInputProtocol? { get set }
    var createExerciseParam : CreateExerciseParam {get}
    func gotoStore()
    func getNumberRow() -> Int
    func getItemIndexPath(indexPath : IndexPath)->String
    func getListQuestionCatelogy()
    func changeLevelParam(indexPath: IndexPath,level: Int)
    func changeNumberQuestion(indexPath: IndexPath,number: Int)
    func gotoCreateExercise(param: CreateExerciseParam)
    func changeNameExercise(name: String)
}

//MARK: Interactor -
protocol CreateExerciseInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getListCatelogySuccessed(respone: [SearchEntity])
    func createExerciseSuccessed(respone: ViewExerciseEntity)
    func upgradeAccount()
}

protocol CreateExerciseInteractorInputProtocol: class {

    var presenter: CreateExerciseInteractorOutputProtocol?  { get set }
    func getListQuestionCatelogy()
    func gotoCreateExercise(param: CreateExerciseParam)
    
    /* Presenter -> Interactor */
}

//MARK: View -
protocol CreateExerciseViewProtocol: class {

    var presenter: CreateExercisePresenterProtocol?  { get set }
    func reloadView()
    func showSumQuestion(sum: Int)
    func upgradeAccount()
    func updateView(enableSubmit: Bool)
    /* Presenter -> ViewController */
}
