//
//  CommentQuestionProtocols.swift
//  EnglishApp
//
//  Created Steve on 8/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol CommentQuestionWireframeProtocol: class {

}
//MARK: Presenter -
protocol CommentQuestionPresenterProtocol: class {

    var interactor: CommentQuestionInteractorInputProtocol? { get set }
    func getComment(idLesson: String,offset: Int)
    func numberParent() -> Int?
    func numberChildren(section: Int) -> Int?
    func getParentComment(section: Int) -> ParentComment?
    func getChildrenComment(indexPath: IndexPath) -> ParentComment?
    func addComment(idLesson: Int, content: String,idParent: Int?,indexSection: Int?)
}

//MARK: Interactor -
protocol CommentQuestionInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getCommentSuccessed(respone: CommentEntity)
    func addCommentSuccessed(respone: ParentComment)
}

protocol CommentQuestionInteractorInputProtocol: class {

    var presenter: CommentQuestionInteractorOutputProtocol?  { get set }
    
    func getComment(idLesson: String,offset:Int)
    func addComment(idLesson: Int, content: String,idParent: Int?)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol CommentQuestionViewProtocol: class {

    var presenter: CommentQuestionPresenterProtocol?  { get set }
    
    func reloadView()

    /* Presenter -> ViewController */
}
