//
//  CommentQuestionInteractor.swift
//  EnglishApp
//
//  Created Steve on 8/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CommentQuestionInteractor: CommentQuestionInteractorInputProtocol {

    weak var presenter: CommentQuestionInteractorOutputProtocol?
    
    func getComment(idLesson: String,offset: Int) {
        ProgressView.shared.show()
        Provider.shared.theoryAPIService.getCommentQuestion(question_details_id: Int(idLesson) ?? 0,offset: offset, success: { (listComment) in
            ProgressView.shared.hide()
            if let _lisComment = listComment {
                self.presenter?.getCommentSuccessed(respone: _lisComment)
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
    
    func addComment(idLesson: Int, content: String,idParent: Int?) {
        Provider.shared.theoryAPIService.addCommentQuestion(question_details_id: idLesson, content: content, parent_id: idParent, success: { (respone) in
            if let _respone = respone {
                self.presenter?.addCommentSuccessed(respone: _respone)
            }
        }) { (error) in
            
        }
    }
}
