//
//  CatelogyExerciseInteractor.swift
//  EnglishApp
//
//  Created Steve on 7/18/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CatelogyExerciseInteractor: CatelogyExerciseInteractorInputProtocol {

    weak var presenter: CatelogyExerciseInteractorOutputProtocol?
    
    func getListCatelogy(offset: Int) {
        
        Provider.shared.exerciseAPIService.getListExerciseCatelogy(offset: offset,success: { (respone) in
            
            if let _respone = respone {
                self.presenter?.getListCatelogySuccessed(respone: _respone)
            }
        }) { (error) in
            
        }
    }
}
