//
//  FightProtocols.swift
//  EnglishApp
//
//  Created Steve on 8/10/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FightWireframeProtocol: class {
    func gotoDetailVocabulary()
    func gotoResult(result: TestResultProfileEntity,type: TypeDoExercise)
}
//MARK: Presenter -
protocol FightPresenterProtocol: class {

    var interactor: FightInteractorInputProtocol? { get set }
    var error: APIError? {get set}
    var exerciseEntity: ViewExerciseEntity? {get set}
    
    func getViewFightCompetition(id: String)
    
    func gotoDetailVocabulary()
    func getTime(index: Int) -> Int?
    func getQuestion(indexPath: IndexPath) -> QuestionEntity?
    func getAllTime() -> [Int]?
    func getAllId() -> [Int]?
    func getIDExercise() -> Int?
    func getTotalTime() -> Int?
    func submitExercise(param: SubmitExerciseParam)
    func exitExercise(id : Int)
    func suggestQuestion(id: String, indexPath: IndexPath, indexQuestion: IndexPath,isDiamond: Bool)
}

//MARK: Interactor -
protocol FightInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getExerciseSuccessed(respone: ViewExerciseEntity)
    func gotoResult(result: TestResultProfileEntity)
    func getExerciseFailed(error:APIError)
    func exitSuccessed(respone: TestResultProfileEntity)
    func suggestQuestionSuccessed(respone: [String])
    func suggestQuestionError(error: APIError)
}

protocol FightInteractorInputProtocol: class {

    var presenter: FightInteractorOutputProtocol?  { get set }
    
    func getViewFightCompetition(id: String)
    
    func getViewEntranceTest()
    func submitExercise(param: SubmitExerciseParam)
    func exitExercise(id : Int)
    func suggestQuestion(id: String,isDiamond: Bool)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol FightViewProtocol: class {

    var presenter: FightPresenterProtocol?  { get set }
    
    func reloadView()
    func getExerciseFailed(error:APIError)
    func exitSuccessed()
    func suggesQuestionSuccessed(indexPath: IndexPath, indexQuestion: IndexPath)
    func suggestQuestionError()

    /* Presenter -> ViewController */
}
