//
//  MoreDictionaryViewController.swift
//  EnglishApp
//
//  Created vinova on 5/15/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import RealmSwift

class MoreDictionaryViewController: ListManagerVC {
    @IBOutlet weak var tbvDictionary: UITableView!
    
	var presenter: MoreDictionaryPresenterProtocol?

    override func setUpViews() {
        showButtonBack = true
        customTitle = LocalizableKey.addDictionary.showLanguage
        super.setUpViews()
    }
    
    override func registerTableView() {
        super.registerTableView()
        self.tableView.registerXibFile(MoreDictionaryCell.self)
    }
    
    override func callAPI() {
        self.presenter?.getListDictionary()
    }
    
    override func cellForRowListManager(item: Any, _ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let data = item as! ItemDictionaryResponse
        let cell = tableView.dequeueTableCell(MoreDictionaryCell.self)
        cell.setupCell(isDownloaded: data.isDownload, title: data.name&)
        cell.actionCell = {[weak self] (isDownloaded) in
            self?.processFile(isDownloaded: isDownloaded,item: data)
        }
        return cell
    }
    
    func processFile(isDownloaded: Bool,item: ItemDictionaryResponse){
        if !isDownloaded {
            let link = BASE_URL + item.link_dictionary&
            ProgressView.shared.show()
            FileZipManager.shared.downLoadFile(link: link) {
                ProgressView.shared.hide()
                item.isDownload = true
                self.tableView.reloadData()
                let object = LocalConfigDictionary(id: item.id ,name: item.name)
                RealmDBManager.share.addObject(value: object)
            }
        } else {
            ProgressView.shared.show()
            RealmDBManager.share.removeAllObject(type: WordEntity.self)
            RealmDBManager.share.removeAllObject(type: WordExplainEntity.self)
            RealmDBManager.share.removeObject(type: LocalConfigDictionary.self,value: item.id)
            item.isDownload = false
            self.tableView.reloadData()
            ProgressView.shared.hide()
        }
    }
}

extension MoreDictionaryViewController : MoreDictionaryViewProtocol {
    func reloadDictionary(data: [ItemDictionaryResponse]){
        initLoadData(data: data)
    }
}
