//
//  FindDetailExerciseRouter.swift
//  EnglishApp
//
//  Created Steve on 12/7/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FindDetailExerciseRouter: FindDetailExerciseWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FindDetailExerciseViewController(nibName: nil, bundle: nil)
        let interactor = FindDetailExerciseInteractor()
        let router = FindDetailExerciseRouter()
        let presenter = FindDetailExercisePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    static func createModule(findDetail: TestResultProfileEntity, isMinusMoney: Bool) -> FindDetailExerciseViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = FindDetailExerciseViewController(nibName: nil, bundle: nil)
        let interactor = FindDetailExerciseInteractor()
        let router = FindDetailExerciseRouter()
        let presenter = FindDetailExercisePresenter(interface: view, interactor: interactor, router: router)
        view.findDetail = findDetail
        view.isMinusMoney = isMinusMoney
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func gotoDetailVocabulary(idWord: Int){
        let vc = DetailLessonRouter.createModule(idWord: idWord)
        self.viewController?.push(controller: vc,animated: true)
    }
}
