//
//  HistoryListExerciseProtocols.swift
//  EnglishApp
//
//  Created Steve on 7/26/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryListExerciseWireframeProtocol: class {
    func gotoResult(type: TypeDoExercise,id: String)
}
//MARK: Presenter -
protocol HistoryListExercisePresenterProtocol: class {

    var interactor: HistoryListExerciseInteractorInputProtocol? { get set }
    var testsResultResponse : TestsResultRespone? {get set}
    func getListHistoryExercise(type: Int,offset: Int,date: String)
    func gotoResult(type: TypeDoExercise,id: String)
}

//MARK: Interactor -
protocol HistoryListExerciseInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getListHistoryExerciseSuccessed(response: TestsResultRespone)
}

protocol HistoryListExerciseInteractorInputProtocol: class {

    var presenter: HistoryListExerciseInteractorOutputProtocol?  { get set }
    func getListHistoryExercise(type: Int,offset: Int,date: String)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HistoryListExerciseViewProtocol: class {

    var presenter: HistoryListExercisePresenterProtocol?  { get set }
    
    func reloadView()

    /* Presenter -> ViewController */
}
