//
//  DetailTeamInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailTeamInteractor: DetailTeamInteractorInputProtocol {

    weak var presenter: DetailTeamInteractorOutputProtocol?
    
    func getDetailTeam(id: String) {
        ProgressView.shared.show()
        Provider.shared.competitionAPIService.getDetailTeam(id: id, success: { (respone) in
            ProgressView.shared.hide()
            if let _respone = respone {
                self.presenter?.getDetailTeamSuccessed(respone: _respone)
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
}
