//
//  DetailTeamInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailTeamInteractor: DetailTeamInteractorInputProtocol {

    weak var presenter: DetailTeamInteractorOutputProtocol?
    
    func getDetailTeam(id: String) {
        ProgressView.shared.show()
        Provider.shared.competitionAPIService.getDetailTeam(id: id, success: { (respone) in
            ProgressView.shared.hide()
            if let _respone = respone {
                self.presenter?.getDetailTeamSuccessed(respone: _respone)
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
    
    func leaveTeam(id: String) {
        ProgressView.shared.show()
        Provider.shared.competitionAPIService.leaveTeam(id: id, success: { (respone) in
            ProgressView.shared.hide()
            if let _ = respone {
                RealmDBManager.share.removeObject(type: LocalConfigCompetition.self, value: Int(UserDefaultHelper.shared.loginUserInfo?.id ?? "0") ?? 0)
                self.presenter?.leaveTeamSuccessed()
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
}
