//
//  BeePackPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/20/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BeePackPresenter: BeePackPresenterProtocol, BeePackInteractorOutputProtocol {

    weak private var view: BeePackViewProtocol?
    var interactor: BeePackInteractorInputProtocol?
    private let router: BeePackWireframeProtocol

    init(interface: BeePackViewProtocol, interactor: BeePackInteractorInputProtocol?, router: BeePackWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
