//
//  ResultExercisePresenter.swift
//  EnglishApp
//
//  Created vinova on 6/25/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ResultExercisePresenter: ResultExercisePresenterProtocol, ResultExerciseInteractorOutputProtocol {

    weak private var view: ResultExerciseViewProtocol?
    var interactor: ResultExerciseInteractorInputProtocol?
    private let router: ResultExerciseWireframeProtocol

    init(interface: ResultExerciseViewProtocol, interactor: ResultExerciseInteractorInputProtocol?, router: ResultExerciseWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
