//
//  QAPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/13/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QAPresenter: QAPresenterProtocol, QAInteractorOutputProtocol {
    var listQA: [QAEntity] = [QAEntity]()
    
    weak private var view: QAViewProtocol?
    var interactor: QAInteractorInputProtocol?
    private let router: QAWireframeProtocol

    init(interface: QAViewProtocol, interactor: QAInteractorInputProtocol?, router: QAWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func getQA() {
        ProgressView.shared.show()
        Provider.shared.qAAPIService.getQA(offset: 0, success: { list in
            ProgressView.shared.hide()
            self.listQA = list
            self.view?.didGetQA(list: self.listQA )
        }) { error in
            ProgressView.shared.hide()
        }
    }
    
    func loadMoreQA() {
        Provider.shared.qAAPIService.getQA(offset: listQA.count, success: { list in
            self.listQA.append(contentsOf: list)
            self.view?.didGetQA(list: self.listQA )
        }) { error in
            
        }
    }
    
    func sendQA(qa: String) {
        ProgressView.shared.show()
        Provider.shared.qAAPIService.sendQA(question: qa, success: { _ in
            self.getQA()
        }) { error in
            ProgressView.shared.hide()
        }
    }
    
}
