//
//  QAPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/13/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QAPresenter: QAPresenterProtocol, QAInteractorOutputProtocol {

    weak private var view: QAViewProtocol?
    var interactor: QAInteractorInputProtocol?
    private let router: QAWireframeProtocol

    init(interface: QAViewProtocol, interactor: QAInteractorInputProtocol?, router: QAWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
