//
//  ForgotPasswordViewController.swift
//  EnglishApp
//
//  Created Kai Pham on 5/11/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForgotPasswordViewController: BaseViewController, ForgotPasswordViewProtocol {

	var presenter: ForgotPasswordPresenterProtocol?
    @IBOutlet weak var btnSendEmail: UIButton!
    @IBOutlet weak var lbMessage: UILabel!
    @IBOutlet weak var vEmail: AppTextField!

	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        addBackToNavigation()
    }
    
    override func setTitleUI() {
        super.setTitleUI()
        
        setTitleNavigation(title: LocalizableKey.ForgotTitle.showLanguage)
        btnSendEmail.setTitle(LocalizableKey.SentEmail.showLanguage, for: .normal)
        lbMessage.text = LocalizableKey.ForgotPasswordMessage.showLanguage
         vEmail.setTitleAndPlaceHolder(title: LocalizableKey.LoginEmail.showLanguage, placeHolder: LocalizableKey.LoginEmailPlaceHolder.showLanguage)
    }
    
    @IBAction func btnSendEmailTapped() {
        
    }
}
