//
//  TaskDateInteractor.swift
//  EnglishApp
//
//  Created vinova on 6/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TaskDateInteractor: TaskDateInteractorInputProtocol {

    weak var presenter: TaskDateInteractorOutputProtocol?
}
