//
//  TaskDatePresenter.swift
//  EnglishApp
//
//  Created vinova on 6/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TaskDatePresenter: TaskDatePresenterProtocol, TaskDateInteractorOutputProtocol {

    weak private var view: TaskDateViewProtocol?
    var interactor: TaskDateInteractorInputProtocol?
    private let router: TaskDateWireframeProtocol

    init(interface: TaskDateViewProtocol, interactor: TaskDateInteractorInputProtocol?, router: TaskDateWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
