//
//  ExplainSolutionGroupRouter.swift
//  EnglishApp
//
//  Created vinova on 6/9/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExplainSolutionGroupRouter: ExplainSolutionGroupWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ExplainSolutionGroupViewController(nibName: nil, bundle: nil)
        let interactor = ExplainSolutionGroupInteractor()
        let router = ExplainSolutionGroupRouter()
        let presenter = ExplainSolutionGroupPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
