//
//  NotificationListViewController.swift
//  EnglishApp
//
//  Created Kai Pham on 6/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NotificationListViewController: BaseViewController, NotificationListViewProtocol {

    @IBOutlet weak var tbNotification: UITableView!
	var presenter: NotificationListPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        configureTable()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
         addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.titleNotification.showLanguage)
    }
    
    override func setTitleUI() {
        super.setTitleUI()
    }

}


extension NotificationListViewController: UITableViewDelegate, UITableViewDataSource {
    func configureTable() {
        tbNotification.delegate = self
        tbNotification.dataSource = self
        tbNotification.registerXibFile(NotificationCell.self)
        tbNotification.separatorStyle = .none
        
        tbNotification.estimatedRowHeight = 55
        tbNotification.rowHeight = UITableView.automaticDimension
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(NotificationCell.self, for: indexPath)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 20
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        self.push(controller: NotificationDetailRouter.createModule())
    }
}
