//
//  NotificationListRouter.swift
//  EnglishApp
//
//  Created Kai Pham on 6/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class NotificationListRouter: NotificationListWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> NotificationListViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = NotificationListViewController.initFromNib()
        let interactor = NotificationListInteractor()
        let router = NotificationListRouter()
        let presenter = NotificationListPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
