//
//  DetailPackProtocols.swift
//  EnglishApp
//
//  Created Kai Pham on 6/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DetailPackWireframeProtocol: class {

}
//MARK: Presenter -
protocol DetailPackPresenterProtocol: class {

    var interactor: DetailPackInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol DetailPackInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DetailPackInteractorInputProtocol: class {

    var presenter: DetailPackInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol DetailPackViewProtocol: class {

    var presenter: DetailPackPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
