//
//  DetailPackPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 6/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DetailPackPresenter: DetailPackPresenterProtocol, DetailPackInteractorOutputProtocol {

    weak private var view: DetailPackViewProtocol?
    var interactor: DetailPackInteractorInputProtocol?
    private let router: DetailPackWireframeProtocol

    init(interface: DetailPackViewProtocol, interactor: DetailPackInteractorInputProtocol?, router: DetailPackWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
