//
//  ChangePasswordPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/12/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChangePasswordPresenter: ChangePasswordPresenterProtocol, ChangePasswordInteractorOutputProtocol {

    weak private var view: ChangePasswordViewProtocol?
    var interactor: ChangePasswordInteractorInputProtocol?
    private let router: ChangePasswordWireframeProtocol

    init(interface: ChangePasswordViewProtocol, interactor: ChangePasswordInteractorInputProtocol?, router: ChangePasswordWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
