//
//  ChangePasswordProtocols.swift
//  EnglishApp
//
//  Created Kai Pham on 5/12/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ChangePasswordWireframeProtocol: class {

}
//MARK: Presenter -
protocol ChangePasswordPresenterProtocol: class {

    var interactor: ChangePasswordInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ChangePasswordInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ChangePasswordInteractorInputProtocol: class {

    var presenter: ChangePasswordInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ChangePasswordViewProtocol: class {

    var presenter: ChangePasswordPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
