//
//  ResultGroupRouter.swift
//  EnglishApp
//
//  Created vinova on 5/23/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ResultGroupRouter: ResultGroupWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ResultGroupViewController.initFromNib()
        let interactor = ResultGroupInteractor()
        let router = ResultGroupRouter()
        let presenter = ResultGroupPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    static func createModule(idCompetition: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ResultGroupViewController.initFromNib()
        view.idCompetition = idCompetition
        let interactor = ResultGroupInteractor()
        let router = ResultGroupRouter()
        let presenter = ResultGroupPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
