//
//  ResultGroupViewController.swift
//  EnglishApp
//
//  Created vinova on 5/23/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class ResultGroupViewController: PageViewController, ResultGroupViewProtocol {

	var presenter: ResultGroupPresenterProtocol?
    var idCompetition: String = "0"

	override func viewDidLoad() {
        super.viewDidLoad()
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.result_competion.showLanguage)
        self.edgesForExtendedLayout = .bottom
        self.tabBarController?.tabBar.isHidden = true
    }
    
    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        return [ResultRouter.createModule(type: .assignExercise, id: idCompetition),ResultCompetitionRouter.createModule(idCompetition: self.idCompetition)]
    }
}
