//
//  MenuInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/9/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class MenuInteractor: MenuInteractorInputProtocol {

    weak var presenter: MenuInteractorOutputProtocol?
}
