//
//  QADetailRouter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/13/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class QADetailRouter: QADetailWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule(qa: QAEntity?) -> QADetailViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = QADetailViewController.initFromNib()
        let interactor = QADetailInteractor()
        let router = QADetailRouter()
        let presenter = QADetailPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        view.qa = qa
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    static func createModule(id: Int) -> QADetailViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = QADetailViewController.initFromNib()
        let interactor = QADetailInteractor()
        let router = QADetailRouter()
        let presenter = QADetailPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        view.id = id
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
