//
//  ExplainCompetitionPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExplainCompetitionPresenter: ExplainCompetitionPresenterProtocol, ExplainCompetitionInteractorOutputProtocol {

    weak private var view: ExplainCompetitionViewProtocol?
    var interactor: ExplainCompetitionInteractorInputProtocol?
    private let router: ExplainCompetitionWireframeProtocol

    init(interface: ExplainCompetitionViewProtocol, interactor: ExplainCompetitionInteractorInputProtocol?, router: ExplainCompetitionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getViewFightTest(idCompetition: String) {
        ProgressView.shared.show()
        Provider.shared.competitionAPIService.getViewFightTest(idCompetition: idCompetition, success: { (response) in
            ProgressView.shared.hide()
            if let _response = response {
                self.view?.getViewFightTestSuccessed(desciption: _response.description&)
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }

}
