//
//  ExplainCompetitionViewController.swift
//  EnglishApp
//
//  Created Kai Pham on 5/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import WebKit

class ExplainCompetitionViewController: BaseViewController {

	var presenter: ExplainCompetitionPresenterProtocol?
    @IBOutlet weak var webView: WKWebView!
    var font = """
    <style>
    @font-face
    {
        font-family: 'Comfortaa';
        font-weight: normal;
        src: url(Comfortaa-Regular.ttf);
    }
    @font-face
    {
        font-family: 'Comfortaa';
        font-weight: bold;
        src: url(Comfortaa-Bold.ttf);
    }
    </style>
    """
    
    var idCompetition : String = ""
    
	override func viewDidLoad() {
        super.viewDidLoad()
        webView.navigationDelegate = self
        webView.scrollView.delegate = self
        self.presenter?.getViewFightTest(idCompetition: idCompetition)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.explainConpetition.showLanguage)
    }
}
extension ExplainCompetitionViewController : ExplainCompetitionViewProtocol {
    func getViewFightTestSuccessed(desciption: String) {
        let htmlString = font + #"<span style="font-family: 'Comfortaa'; font-weight: Regular; font-size: 14; color: black">"# + desciption + #"</span>"#
        webView.loadHTMLString(htmlString, baseURL: Bundle.main.bundleURL)
    }
}

extension ExplainCompetitionViewController : UIScrollViewDelegate {
    func viewForZooming(in scrollView: UIScrollView) -> UIView? {
        return nil
    }
}

extension ExplainCompetitionViewController: WKNavigationDelegate {
    func webView(_ webView: WKWebView, didCommit navigation: WKNavigation!) {
         let jscript = "var meta = document.createElement('meta'); meta.setAttribute('name', 'viewport'); meta.setAttribute('content', 'width=device-width'); document.getElementsByTagName('head')[0].appendChild(meta);"
        webView.evaluateJavaScript(jscript)
    }
}
