//
//  VocabularyPresenter.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VocabularyPresenter: VocabularyPresenterProtocol, VocabularyInteractorOutputProtocol {

    weak private var view: VocabularyViewProtocol?
    var interactor: VocabularyInteractorInputProtocol?
    private let router: VocabularyWireframeProtocol

    init(interface: VocabularyViewProtocol, interactor: VocabularyInteractorInputProtocol?, router: VocabularyWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
