//
//  VocabularyViewController.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class VocabularyViewController: UIViewController, VocabularyViewProtocol {

    @IBOutlet weak var tbvVocabulary: UITableView!
    var presenter: VocabularyPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        tbvVocabulary.registerXibFile(CellGrammar.self)
        tbvVocabulary.dataSource = self
        tbvVocabulary.delegate = self
    }
}
extension VocabularyViewController : UITableViewDataSource{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(CellGrammar.self, for: indexPath)
        return cell
    }
}
extension VocabularyViewController: UITableViewDelegate{
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 50
    }
}
extension VocabularyViewController: IndicatorInfoProvider{
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.vocabulary.showLanguage)
    }
}
