//
//  PageViewCompetitionRouter.swift
//  EnglishApp
//
//  Created Steve on 12/1/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PageViewCompetitionRouter: PageViewCompetitionWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = PageViewCompetitionViewController(nibName: nil, bundle: nil)
        let interactor = PageViewCompetitionInteractor()
        let router = PageViewCompetitionRouter()
        let presenter = PageViewCompetitionPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
