//
//  SelectTeamInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/13/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SelectTeamInteractor: SelectTeamInteractorInputProtocol {

    weak var presenter: SelectTeamInteractorOutputProtocol?
}
