//
//  CommentViewController.swift
//  EnglishApp
//
//  Created vinova on 5/18/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CommentViewController: BaseViewController, CommentViewProtocol {

    @IBOutlet weak var tbvComment: UITableView!
    var presenter: CommentPresenterProtocol?

    override func setUpViews() {
        super.setUpViews()
        tbvComment.registerXibFile(CellComment.self)
        tbvComment.registerXibFile(CellHeaderComment.self)
        tbvComment.delegate = self
        tbvComment.dataSource = self
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        setTitleNavigation(title: LocalizableKey.comment.showLanguage)
    }
}

extension CommentViewController : UITableViewDataSource{
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.row % 2 == 0{
            let cell = tableView.dequeue(CellHeaderComment.self, for: indexPath)
            return cell
        }
        let cell = tableView.dequeue(CellComment.self, for: indexPath)
        return cell
    }
}

extension CommentViewController : UITableViewDelegate{
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
}
