//
//  ProfileViewController.swift
//  EnglishApp
//
//  Created Kai Pham on 5/12/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ProfileViewController: BaseViewController {

	var presenter: ProfilePresenterProtocol?
    @IBOutlet weak var tableView: UITableView!

    var user = UserEntity() {
        didSet {
            tableView.reloadData()
            tableView.isHidden = false
        }
    }
    
    var package = [Inventories]() {
        didSet {
            tableView.reloadData()
            tableView.isHidden = false
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        setTitleNavigation(title: LocalizableKey.TitleProfile.showLanguage)
        setUpTableView()
        tableView.isHidden = true
    }
    
    func setUpTableView() {
        tableView.delegate = self
        tableView.dataSource = self
        tableView.registerXibFile(PackageCell.self)
        tableView.registerXibFile(ProfileHeader.self)
        tableView.registerXibFile(HomeTitleCell.self)
        tableView.registerXibFile(HomeNoResultCell.self)
        tableView.separatorStyle = .none
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        presenter?.getPackage()
        presenter?.getProfile()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        hideTabbar()
        
        addBackToNavigation()
        addButtonToNavigation(image: AppImage.imgEditProfile, style: .right, action: #selector(btnEditTapped))
        
    }
    
    override func btnBackTapped() {
        showTabbar()
        self.pop()
    }
    
    @objc func btnEditTapped() {
        self.push(controller: EditProfileRouter.createModule())
    }

}

extension ProfileViewController: ProfileViewProtocol {
    func didGetProfile(user: UserEntity) {
        self.user = user
        UserDefaultHelper.shared.saveUser(user: user)
    }
    
    func didGetPackage(package: [Inventories]) {
        self.package = package
    }
}

extension ProfileViewController: UITableViewDelegate, UITableViewDataSource {
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if section == 0 {
            return 1
        } else {
            if presenter?.lisPackage.count == 0 {
                return 2
            }
            return (presenter?.lisPackage.count ?? 0) + 1
        }
    }

    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.section == 0 {
            let cell = tableView.dequeue(ProfileHeader.self, for: indexPath)
            cell.delegate = self
            cell.user = self.user
            return cell
        } else {
            if indexPath.row == 0 {
                let cell = tableView.dequeue(HomeTitleCell.self, for: indexPath)
                cell.contentView.backgroundColor = .white
                cell.lbTitle.text = LocalizableKey.userPackage.showLanguage
                return cell
            } else {
                if (presenter?.lisPackage.count ?? 0) == 0 {
                    let cell = tableView.dequeue(HomeNoResultCell.self, for: indexPath)
                    cell.showNoData()
                    return cell
                } else {
                    let cell = tableView.dequeue(PackageCell.self, for: indexPath)
                    cell.lbTitle.text = self.package[indexPath.row - 1].name
                    let date = self.package[indexPath.row - 1].expiredTime?.toString(dateFormat: AppDateFormat.hhmmddmmyyy).replacingOccurrences(of: "-", with: "/")
                    cell.lbTime.text = "\(LocalizableKey.dateExpire.showLanguage)" +  date&
                    return cell
                }
                
            }
        }
    }

    func numberOfSections(in tableView: UITableView) -> Int {
        return 2
    }
}

extension ProfileViewController: ProfileHeaderDelegate {
    func btnBeeTapped() {
        self.push(controller: HistoryBeeRouter.createModule(wallet_type: 3))
    }
    
    func btnDiamondTapped() {
        self.push(controller: HistoryBeeRouter.createModule(wallet_type: 1))
    }
}
