//
//  ListLessonRouter.swift
//  EnglishApp
//
//  Created vinova on 5/18/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ListLessonRouter: ListLessonWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ListLessonViewController(nibName: nil, bundle: nil)
        let interactor = ListLessonInteractor()
        let router = ListLessonRouter()
        let presenter = ListLessonPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    static func createModule(type: LessonRecipe = .lesson,lesson_category_id: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ListLessonViewController(nibName: nil, bundle: nil)
        view.type = type
        view.lesson_category_id = lesson_category_id
        let interactor = ListLessonInteractor()
        let router = ListLessonRouter()
        let presenter = ListLessonPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
