//
//  SignUpViewController.swift
//  EnglishApp
//
//  Created Kai Pham on 5/11/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class SignUpViewController: UIViewController, SignUpViewProtocol {

	var presenter: SignUpPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
