//
//  SignUpProtocols.swift
//  EnglishApp
//
//  Created Kai Pham on 5/11/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol SignUpWireframeProtocol: class {

}
//MARK: Presenter -
protocol SignUpPresenterProtocol: class {

    var interactor: SignUpInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol SignUpInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol SignUpInteractorInputProtocol: class {

    var presenter: SignUpInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol SignUpViewProtocol: class {

    var presenter: SignUpPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
