//
//  LessonViewController.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

enum TheoryType {
    case lesson
    case recipe
}

class LessonViewController: UIViewController, LessonViewProtocol {

	var presenter: LessonPresenterProtocol?
    var type: TheoryType = .lesson

    @IBAction func clickPhrasalVerbs(_ sender: Any) {
        
    }
    
    @IBAction func clickGrammar(_ sender: Any) {
        
    }
    
    @IBAction func clickPhonetics(_ sender: Any) {
        
    }
    
    @IBOutlet weak var lbPhrasalVerbs: UILabel!
    @IBOutlet weak var vPhrasalVerbs: ViewGradient!
    @IBOutlet weak var vGrammar: ViewGradient!
    @IBOutlet weak var vPhonetics: ViewGradient!
    @IBOutlet weak var lbGrammar: UILabel!
    @IBOutlet weak var lbPhonetics: UILabel!
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        if type == .lesson {
            lbGrammar.text = LocalizableKey.grammar.showLanguage
            lbPhonetics.text = LocalizableKey.phonetics.showLanguage
            lbPhrasalVerbs.text = LocalizableKey.phrasal_verbs.showLanguage
        }
        
        if type == .recipe {
            lbGrammar.text = LocalizableKey.wordUsage.showLanguage
            lbPhonetics.text = LocalizableKey.wordForm.showLanguage
            lbPhrasalVerbs.text = LocalizableKey.idiams.showLanguage
        }
        
        vPhrasalVerbs.setupGradient(beginColor: #colorLiteral(red: 0.7254902124, green: 0.4784313738, blue: 0.09803921729, alpha: 1), endColor: #colorLiteral(red: 0.7254902124, green: 0.4784313738, blue: 0.09803921729, alpha: 1))
        vGrammar.setupGradient(beginColor: #colorLiteral(red: 0.3098039216, green: 0.6745098039, blue: 0.9960784314, alpha: 1), endColor: #colorLiteral(red: 0.3098039216, green: 0.6745098039, blue: 0.9960784314, alpha: 1))
        vPhonetics.setupGradient(beginColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.7254901961, alpha: 1), endColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.7254901961, alpha: 1))
        
    }

}

extension LessonViewController: IndicatorInfoProvider{
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        if type == .lesson {
            return IndicatorInfo(title: LocalizableKey.lesson.showLanguage)
        }
        return IndicatorInfo(title: LocalizableKey.recipe.showLanguage)
    }
}

