//
//  LessonRouter.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LessonRouter: LessonWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LessonViewController(nibName: nil, bundle: nil)
        let interactor = LessonInteractor()
        let router = LessonRouter()
        let presenter = LessonPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    static func createModule(type: TheoryType = .lesson) -> LessonViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = LessonViewController(nibName: nil, bundle: nil)
        view.type = type
        let interactor = LessonInteractor()
        let router = LessonRouter()
        let presenter = LessonPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
    
    func gotoListLesson(id: String) {
        let vc = ListLessonRouter.createModule(lesson_category_id: id)
        self.viewController?.push(controller: vc)
    }
}
