//
//  ExplainExerciseViewController.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExplainExerciseViewController: BaseViewController, ExplainExerciseViewProtocol {

	var presenter: ExplainExercisePresenterProtocol?

    @IBOutlet weak var lblExplainQuestion: UILabel!
    
    var id: Int = 0
    
    override func setUpViews() {
        super.setUpViews()
        
    }

}
