//
//  ExplainExerciseGroupProtocols.swift
//  EnglishApp
//
//  Created Steve on 7/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ExplainExerciseGroupWireframeProtocol: class {

}
//MARK: Presenter -
protocol ExplainExerciseGroupPresenterProtocol: class {

    var interactor: ExplainExerciseGroupInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ExplainExerciseGroupInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol ExplainExerciseGroupInteractorInputProtocol: class {

    var presenter: ExplainExerciseGroupInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ExplainExerciseGroupViewProtocol: class {

    var presenter: ExplainExerciseGroupPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
