//
//  ExplainExerciseGroupPresenter.swift
//  EnglishApp
//
//  Created Steve on 7/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExplainExerciseGroupPresenter: ExplainExerciseGroupPresenterProtocol, ExplainExerciseGroupInteractorOutputProtocol {

    weak private var view: ExplainExerciseGroupViewProtocol?
    var interactor: ExplainExerciseGroupInteractorInputProtocol?
    private let router: ExplainExerciseGroupWireframeProtocol

    init(interface: ExplainExerciseGroupViewProtocol, interactor: ExplainExerciseGroupInteractorInputProtocol?, router: ExplainExerciseGroupWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
