//
//  ExplainExerciseGroupViewController.swift
//  EnglishApp
//
//  Created Steve on 7/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class ExplainExerciseGroupViewController: PageViewController, ExplainExerciseGroupViewProtocol {

	var presenter: ExplainExerciseGroupPresenterProtocol?
    var id: Int = 0

	override func viewDidLoad() {
        super.viewDidLoad()
        self.tabBarController?.tabBar.isHidden = true
        self.edgesForExtendedLayout = UIRectEdge.bottom
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.explain_question.showLanguage)
        
    }
    
    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        return [ExplainExerciseRouter.createModule(id: id),CommentRouter.createModule(id: String(id))]
    }

}
