//
//  ExplainExerciseGroupInteractor.swift
//  EnglishApp
//
//  Created Steve on 7/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExplainExerciseGroupInteractor: ExplainExerciseGroupInteractorInputProtocol {

    weak var presenter: ExplainExerciseGroupInteractorOutputProtocol?
}
