//
//  BXHInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 6/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BXHInteractor: BXHInteractorInputProtocol {

    weak var presenter: BXHInteractorOutputProtocol?
}
