//
//  BXHProtocols.swift
//  EnglishApp
//
//  Created Kai Pham on 6/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol BXHWireframeProtocol: class {

}
//MARK: Presenter -
protocol BXHPresenterProtocol: class {

    var interactor: BXHInteractorInputProtocol? { get set }
    func getListLeaderBoard(quarter: String, year: String, rank: String)
    func loadMore(quarter: String, year: String, rank: String)
    var canLoadMore: Bool { get set }
    var listUser: [UserEntity] { get set }
}

//MARK: Interactor -
protocol BXHInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol BXHInteractorInputProtocol: class {

    var presenter: BXHInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol BXHViewProtocol: class {

    var presenter: BXHPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func didGetList(listLeaderBoard: LeaderBoardEntity)
    func didLoadMore()
    func didGetList(error: Error)
}
