//
//  BXHViewController.swift
//  EnglishApp
//
//  Created Kai Pham on 6/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class BXHViewController: BaseViewController {

	var presenter: BXHPresenterProtocol?
    @IBOutlet weak var tbBXH: UITableView!

    var listLeaderBoard = LeaderBoardEntity(){
        didSet{
            tbBXH.reloadData()
        }
    }
    
	override func viewDidLoad() {
        super.viewDidLoad()
        presenter?.getListLeaderBoard(quarter: 2, year: 2019)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        
        hideTabbar()
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.bxh.showLanguage)
    }
    override func setUpViews() {
        super.setUpViews()
        configureTable()
    }

    override func btnBackTapped() {
        showTabbar()
        self.pop()
    }
}


extension BXHViewController: UITableViewDelegate, UITableViewDataSource {
    func configureTable() {
        tbBXH.delegate = self
        tbBXH.dataSource = self
        tbBXH.registerXibFile(BXHCell.self)
        tbBXH.registerXibFile(BXHTop3Cell.self)
        tbBXH.separatorStyle = .none
        
        tbBXH.estimatedRowHeight = 55
        tbBXH.rowHeight = UITableView.automaticDimension
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if indexPath.item == 0 {
            let cell = tableView.dequeue(BXHTop3Cell.self, for: indexPath)
            if let topThree = listLeaderBoard.boards{
                cell.viewTopThree.listTopThree = topThree
            }
            
            return cell
        }
        
        let cell = tableView.dequeue(BXHCell.self, for: indexPath)
        if let _listLeaderBoard = listLeaderBoard.boards{
            cell.viewBXH.number = indexPath.item + 3
            cell.viewBXH.user = _listLeaderBoard[indexPath.item + 2]
        }
        return cell
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return (listLeaderBoard.total ?? 0) - 2
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return indexPath.item == 0 ? 150: 78 
    }
}
extension BXHViewController: BXHViewProtocol{
    func didGetList(listLeaderBoard: LeaderBoardEntity) {
        self.listLeaderBoard = listLeaderBoard
    }
    
    func didGetList(error: Error) {
        print(error.localizedDescription)
    }
    
    
}
