//
//  AssignExerciseViewController.swift
//  EnglishApp
//
//  Created Steve on 7/18/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AssignExerciseViewController: BaseViewController {

	var presenter: AssignExercisePresenterProtocol?
    
    @IBOutlet weak var tbvAssignExercise: UITableView!

    
    var offset: Int = 0
    
    override func setUpViews() {
        super.setUpViews()
        tbvAssignExercise.registerXibFile(CellAssignExercise.self)
        tbvAssignExercise.dataSource = self
        tbvAssignExercise.delegate = self

    }
    override func setUpNavigation() {
        super.setUpNavigation()
        self.tabBarController?.tabBar.isHidden = true
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.assign_exercise.showLanguage)
    }
    
}

extension AssignExerciseViewController : AssignExerciseViewProtocol{
    func reloadView() {
        tbvAssignExercise.reloadData()
    }
}

extension AssignExerciseViewController : UITableViewDataSource{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(CellAssignExercise.self, for: indexPath)
        return cell
    }
    func tableView(_ tableView: UITableView, willDisplay cell: UITableViewCell, forRowAt indexPath: IndexPath) {
        
    }
}
extension AssignExerciseViewController : UITableViewDelegate{
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
}
