//
//  ChoiceExercisePresenter.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChoiceExercisePresenter: ChoiceExercisePresenterProtocol, ChoiceExerciseInteractorOutputProtocol {

    weak private var view: ChoiceExerciseViewProtocol?
    var interactor: ChoiceExerciseInteractorInputProtocol?
    private let router: ChoiceExerciseWireframeProtocol

    init(interface: ChoiceExerciseViewProtocol, interactor: ChoiceExerciseInteractorInputProtocol?, router: ChoiceExerciseWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
