//
//  ChoiceExerciseInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChoiceExerciseInteractor: ChoiceExerciseInteractorInputProtocol {

    weak var presenter: ChoiceExerciseInteractorOutputProtocol?
}
