//
//  DailyMissionProtocols.swift
//  EnglishApp
//
//  Created Kai Pham on 5/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol DailyMissionWireframeProtocol: class {

}
//MARK: Presenter -
protocol DailyMissionPresenterProtocol: class {

    var interactor: DailyMissionInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol DailyMissionInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol DailyMissionInteractorInputProtocol: class {

    var presenter: DailyMissionInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol DailyMissionViewProtocol: class {

    var presenter: DailyMissionPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
