//
//  DailyMissionViewController.swift
//  EnglishApp
//
//  Created Kai Pham on 5/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DailyMissionViewController: BaseViewController, DailyMissionViewProtocol {

	var presenter: DailyMissionPresenterProtocol?
    @IBOutlet weak var btnStart: UIButton!
    @IBOutlet weak var lbMessage: UILabel!

	override func viewDidLoad() {
        super.viewDidLoad()
    }

    override func setTitleUI() {
        super.setTitleUI()
        
        hideTabbar()
        
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.dailyMissionTitle.showLanguage)
        btnStart.setTitle(LocalizableKey.startMission.showLanguage.showLanguage.uppercased(), for: .normal)
        lbMessage.text = LocalizableKey.messageDailyMission.showLanguage
    }
    
    @IBAction func btnStartTapped() {
        let vc = NameExerciseRouter.createModule()
        self.push(controller: vc)
    }
    
    override func btnBackTapped() {
        showTabbar()
        self.pop()
    }
}
