//
//  DailyMissionInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/16/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DailyMissionInteractor: DailyMissionInteractorInputProtocol {

    weak var presenter: DailyMissionInteractorOutputProtocol?
}
