//
//  EditProfileProtocols.swift
//  EnglishApp
//
//  Created Kai Pham on 5/12/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol EditProfileWireframeProtocol: class {

}
//MARK: Presenter -
protocol EditProfilePresenterProtocol: class {

    var interactor: EditProfileInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol EditProfileInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol EditProfileInteractorInputProtocol: class {

    var presenter: EditProfileInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol EditProfileViewProtocol: class {

    var presenter: EditProfilePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
