//
//  VocabularyViewController.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class VocabularyViewController: ListManagerVC {

	var presenter: VocabularyPresenterProtocol?
    var isDelete = false
    var actionDeleteFinish : (()->())?
    var listDelete : [Int] = []

    override func setUpViews() {
        showButtonBack = false
        super.setUpViews()
    }
    override func registerTableView() {
        super.registerTableView()
        tableView.registerXibFile(CellGrammar.self)
    }
    override func callAPI() {
        super.callAPI()
        self.presenter?.getListLikeVocab(offset: self.offset)
    }
    
    override func viewDidDisappear(_ animated: Bool) {
        super.viewDidDisappear(true)
        self.cancelDelete()
        actionDeleteFinish?()
    }

    func notifyDelete(){
        PopUpHelper.shared.showComfirmPopUp(message: LocalizableKey.cofirm_delete.showLanguage, titleYes: LocalizableKey.confirm.showLanguage.uppercased(), titleNo: LocalizableKey.cancel.showLanguage.uppercased()) { [unowned self] in
            self.presenter?.deleteVocab(listId: self.listDelete)
        }
    }
    
    func deleteVocabulary() {
        let listVocabulary = self.listData as! [WordLikeEntity]
        let listId = listVocabulary.filter{$0.isDelete}.map{Int($0._id ?? "0")}.compactMap{$0}
        self.listDelete = listId
        if listDelete.count > 0 {
            self.notifyDelete()
        } else {
            self.reloadViewAfterDelete()
        }
    }

    override func cellForRowListManager(item: Any, _ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let data = item as! WordLikeEntity
        let cell = tableView.dequeue(CellGrammar.self, for: indexPath)
        cell.indexPath = indexPath
        cell.setupTitle(title: data.word&)

        if isDelete {
            cell.setupDelete()
            cell.actionClick = {[weak self] (_) in
               data.isDelete = !data.isDelete
            }
        } else {
            cell.setupNoDelete()
        }
        
        return cell
    }
    
    func reloadViewAfterDelete(){
        isDelete = false
        tableView.reloadData()
        actionDeleteFinish?()
    }
    
    override func didSelectTableView(item: Any, indexPath: IndexPath) {
        if !isDelete {
            let data = item as! WordLikeEntity
            let vc = DetailLessonRouter.createModule(idVocabulary: Int(data.word_id ?? "0") ?? 0)
            vc.callbackCallAgainAPI = {[weak self] in
                self?.callAPIAgain()
            }
            self.push(controller: vc)
        }
    }
    
    func callAPIAgain(){
        self.offset = 0
        callAPI()
    }
    
    func cancelDelete() {
        let listVocabulary = self.listData as! [WordLikeEntity]
        for item in listVocabulary {
            item.isDelete = false
        }
        reloadViewAfterDelete()
    }
}
extension VocabularyViewController : VocabularyViewProtocol{
    func reloadView(listResponse: [WordLikeEntity]) {
        initLoadData(data: listResponse)
    }
    
    func deleteVocabSuccessed() {
        let listVocabulary = self.listData as! [WordLikeEntity]
        self.listData = listVocabulary.filter{!$0.isDelete}
        reloadViewAfterDelete()
    }
   
}

extension VocabularyViewController: IndicatorInfoProvider{
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.vocabulary.showLanguage)
    }
}

