//
//  VocabularyInteractor.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VocabularyInteractor: VocabularyInteractorInputProtocol {

    weak var presenter: VocabularyInteractorOutputProtocol?
}
