//
//  VocabularyInteractor.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class VocabularyInteractor: VocabularyInteractorInputProtocol {

    weak var presenter: VocabularyInteractorOutputProtocol?
    
    func getListLikeVocab(offset: Int) {
        ProgressView.shared.show()
        Provider.shared.saveAPIService.getListLikeVocab(offset: offset, success: { (response) in
            ProgressView.shared.hide()
            if let _reponse = response {
                self.presenter?.getListLikeVocabSuccessed(response: _reponse)
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
    
    func deleteVocab(listId: [Int]) {
        ProgressView.shared.show()
        Provider.shared.saveAPIService.deleteVocabulary(ids: listId, success: { (response) in
            ProgressView.shared.hide()
            if let _ = response {
                self.presenter?.deleteVocabSuccessed()
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
}
