//
//  VocabularyProtocols.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol VocabularyWireframeProtocol: class {

}
//MARK: Presenter -
protocol VocabularyPresenterProtocol: class {

    var interactor: VocabularyInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol VocabularyInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol VocabularyInteractorInputProtocol: class {

    var presenter: VocabularyInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol VocabularyViewProtocol: class {

    var presenter: VocabularyPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
