//
//  TryHardProtocols.swift
//  EnglishApp
//
//  Created vinova on 6/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TryHardWireframeProtocol: class {

}
//MARK: Presenter -
protocol TryHardPresenterProtocol: class {

    var interactor: TryHardInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol TryHardInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol TryHardInteractorInputProtocol: class {

    var presenter: TryHardInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol TryHardViewProtocol: class {

    var presenter: TryHardPresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
