//
//  StudyPackPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 5/20/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class StudyPackPresenter: StudyPackPresenterProtocol, StudyPackInteractorOutputProtocol {

    weak private var view: StudyPackViewProtocol?
    var interactor: StudyPackInteractorInputProtocol?
    private let router: StudyPackWireframeProtocol

    init(interface: StudyPackViewProtocol, interactor: StudyPackInteractorInputProtocol?, router: StudyPackWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
