//
//  DailyMissonRouter.swift
//  EnglishApp
//
//  Created Steve on 7/19/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class DailyMissonRouter: DailyMissonWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = DailyMissonViewController(nibName: nil, bundle: nil)
        let interactor = DailyMissonInteractor()
        let router = DailyMissonRouter()
        let presenter = DailyMissonPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func gotoDailyMisson() {
        let vc = NameExerciseRouter.createModule(type: .dailyMissonExercise)
        viewController?.push(controller: vc)
    }
}
