//
//  PreviewProfileInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 5/12/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class PreviewProfileInteractor: PreviewProfileInteractorInputProtocol {

    weak var presenter: PreviewProfileInteractorOutputProtocol?
}
