//
//  LevelExerciseProtocols.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol LevelExerciseWireframeProtocol: class {
    func gotoCatelogy(studyPackId: Int)
}
//MARK: Presenter -
protocol LevelExercisePresenterProtocol: class {

    var interactor: LevelExerciseInteractorInputProtocol? { get set }
    
    func getLevelExercise(type_test: Int,offset: Int)
    func gotoCatelogy(studyPackId: Int)

}

//MARK: Interactor -
protocol LevelExerciseInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    
    func getListLevelExerciseSuccessed(respone: LevelExerciseEntity)
    
}

protocol LevelExerciseInteractorInputProtocol: class {

    var presenter: LevelExerciseInteractorOutputProtocol?  { get set }
    
    func getLevelExercise(type_test: Int,offset: Int)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol LevelExerciseViewProtocol: class {

    var presenter: LevelExercisePresenterProtocol?  { get set }
    func reloadView(listData: [SearchEntity])

    /* Presenter -> ViewController */
}
