//
//  LevelExerciseInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LevelExerciseInteractor: LevelExerciseInteractorInputProtocol {
    

    weak var presenter: LevelExerciseInteractorOutputProtocol?
    
    func getLevelExercise(type_test: Int,offset: Int) {
        
        Provider.shared.exerciseAPIService.getLevelExercise(type_test: type_test, offset: offset, success: { (respone) in
            
            if let _respone = respone {
                self.presenter?.getListLevelExerciseSuccessed(respone: _respone)
            }
        }) { (error) in
            
        }
    }
}

    
