//
//  LevelExerciseViewController.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


enum AssignLevel {
    case assign
    case level
    case tryhard
}

class LevelExerciseViewController: BaseViewController, LevelExerciseViewProtocol {

	var presenter: LevelExercisePresenterProtocol?
    
    @IBOutlet weak var tbvLevelExercise: UITableView!
    var type: AssignLevel = .level
    
    override func setUpViews() {
        super.setUpViews()
        if type == .level || type == .tryhard {
            tbvLevelExercise.registerXibFile(CellLevelExercise.self)
        } else {
            tbvLevelExercise.registerXibFile(CellAssignExercise.self)
        }
        tbvLevelExercise.dataSource = self
        tbvLevelExercise.delegate = self
    }
    override func setUpNavigation() {
        super.setUpNavigation()
        self.tabBarController?.tabBar.isHidden = true
        addBackToNavigation()
        if type == .level {
            setTitleNavigation(title: LocalizableKey.level_exercise.showLanguage)
        }
        
        if type == .tryhard{
            setTitleNavigation(title: LocalizableKey.try_hard.showLanguage)
        }
        if type == .assign{
            setTitleNavigation(title: LocalizableKey.assign_exercise.showLanguage)
        }
    }

}
extension LevelExerciseViewController : UITableViewDataSource{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if type == .level || type == .tryhard {
            let cell = tableView.dequeue(CellLevelExercise.self, for: indexPath)
            return cell
        }
        let cell = tableView.dequeue(CellAssignExercise.self, for: indexPath)
        return cell
    }
}
extension LevelExerciseViewController : UITableViewDelegate{
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if type == .tryhard {
            self.presenter?.gotoChoiceExercise()
        }
        
        if type == .level{
            self.presenter?.gotoTryHard()
        }
        
        if type == .assign{
            self.presenter?.gotoExercise()
        }
        
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return UITableView.automaticDimension
    }
    func tableView(_ tableView: UITableView, estimatedHeightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
}
