//
//  LevelExerciseViewController.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class LevelExerciseViewController: BaseViewController, LevelExerciseViewProtocol {

	var presenter: LevelExercisePresenterProtocol?
    
    @IBOutlet weak var tbvLevelExercise: UITableView!
    
    override func setUpViews() {
        super.setUpViews()
        tbvLevelExercise.registerXibFile(CellLevelExercise.self)
        tbvLevelExercise.dataSource = self
        tbvLevelExercise.delegate = self
    }
    override func setUpNavigation() {
        super.setUpNavigation()
        setTitleNavigation(title: LocalizableKey.level_exercise.showLanguage)
        addBackToNavigation()
    }

}
extension LevelExerciseViewController : UITableViewDataSource{
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return 10
    }
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeue(CellLevelExercise.self, for: indexPath)
        return cell
    }
}
extension LevelExerciseViewController : UITableViewDelegate{
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        
    }
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 60
    }
}
