//
//  AddNoteInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class AddNoteInteractor: AddNoteInteractorInputProtocol {

    weak var presenter: AddNoteInteractorOutputProtocol?
    
    func addNote(description: String){
        ProgressView.shared.show()
        Provider.shared.saveAPIService.addNote(description: description, success: { (respone) in
            ProgressView.shared.hide()
            if let _ = respone {
                self.presenter?.addNoteSuccessed()
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
}
