//
//  DetailLessonViewController.swift
//  EnglishApp
//
//  Created vinova on 5/18/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit


enum DetailLessonVocabulary{
    case detailLesson
    case vocabulary
}
class DetailLessonViewController: BaseViewController, DetailLessonViewProtocol {

	var presenter: DetailLessonPresenterProtocol?
    var titleNavi: String = ""
    var type : DetailLessonVocabulary = .detailLesson
    
    var viewMessage = ViewMessage(frame: CGRect(x: 0, y: 0, width: 24, height: 24))
    override func setUpViews() {
        super.setUpViews()
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
        setTitleNavigation(title: titleNavi)
        if type == .detailLesson{
            viewMessage.action = {
                print("Message")
            }
            addTwoViewToNavigation(view1: viewMessage, image1: nil,action1: nil, view2: nil, image2: UIImage(named:"Material_Icons_white_favorite")!, action2: #selector(clickHeart))
        } else {
            addButtonToNavigation(image: UIImage(named:"Material_Icons_white_favorite")!, style: .right, action: #selector(clickHeart))
        }
        
    }
    
    @objc func clickHeart(){
        
    }
}
