//
//  NameExerciseProtocols.swift
//  EnglishApp
//
//  Created vinova on 5/23/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol NameExerciseWireframeProtocol: class {
    func gotoDetailVocabulary()
    func gotoResult(result: TestResultProfileEntity,type: TypeDoExercise)
}
//MARK: Presenter -
protocol NameExercisePresenterProtocol: class {

    var interactor: NameExerciseInteractorInputProtocol? { get set }
    var type : TypeDoExercise {get set}
    var exerciseEntity: ViewExerciseEntity? {get set}
    var error: APIError? {get set}
    
    func gotoDetailVocabulary()
    func getViewExercise(id: String)
    func getViewEntranceTest()
    func getTime(index: Int) -> Int?
    func getQuestion(indexPath: IndexPath) -> QuestionEntity?
    func getAllTime() -> [Int]?
    func submitExercise(param: SubmitExerciseParam)
    func getDailyMisson()
    func exitExercise(id : Int)
    func suggestQuestion(id: String, indexPath: IndexPath, indexQuestion: IndexPath,isDiamond: Bool)
    
}

//MARK: Interactor -
protocol NameExerciseInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getExerciseSuccessed(respone: ViewExerciseEntity)
    func gotoResult(result: TestResultProfileEntity)
    func getExerciseFailed(error:APIError)
    func exitSuccessed(respone: TestResultProfileEntity)
    func suggestQuestionSuccessed(respone: [String])
    func suggestQuestionError(error: APIError)
}

protocol NameExerciseInteractorInputProtocol: class {

    var presenter: NameExerciseInteractorOutputProtocol?  { get set }
    func getViewExercise(id: String)
    func getViewEntranceTest()
    func submitExercise(param: SubmitExerciseParam)
    func getDailyMisson()
    func exitExercise(id : Int)
    func suggestQuestion(id: String,isDiamond: Bool)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol NameExerciseViewProtocol: class {

    var presenter: NameExercisePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func reloadView()
    func getExerciseFailed(error:APIError)
    func exitSuccessed()
    func suggesQuestionSuccessed(indexPath: IndexPath, indexQuestion: IndexPath)
    func suggestQuestionError()
}
