//
//  NameExerciseProtocols.swift
//  EnglishApp
//
//  Created vinova on 5/23/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol NameExerciseWireframeProtocol: class {
    func gotoDetailVocabulary()
    func gotoResult()
}
//MARK: Presenter -
protocol NameExercisePresenterProtocol: class {

    var interactor: NameExerciseInteractorInputProtocol? { get set }
    func gotoDetailVocabulary()
    func gotoResult()
    func getViewExercise()
    func getViewEntranceTest()
    func getTime(index: Int) -> Int?
    func getNumber() -> Int?
    func getQuestion(indexPath: IndexPath) -> QuestionEntity?
}

//MARK: Interactor -
protocol NameExerciseInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getExerciseSuccessed(respone: ViewExerciseEntity)
}

protocol NameExerciseInteractorInputProtocol: class {

    var presenter: NameExerciseInteractorOutputProtocol?  { get set }
    func getViewExercise()
    func getViewEntranceTest()

    /* Presenter -> Interactor */
}

//MARK: View -
protocol NameExerciseViewProtocol: class {

    var presenter: NameExercisePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
    func reloadView()
}
