//
//  HistoryDailyMissonInteractor.swift
//  EnglishApp
//
//  Created Steve on 7/19/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryDailyMissonInteractor: HistoryDailyMissonInteractorInputProtocol {

    weak var presenter: HistoryDailyMissonInteractorOutputProtocol?
    
    func getHistoryExercise(type: Int,date: String,offset: Int) {
        Provider.shared.exerciseAPIService.getHistoryExercise(type: type,date: date, offset: offset, success: { (respone) in
            if let _respone = respone {
                self.presenter?.getHistoryDailyMissonSuccessed(listLesson: _respone.results)
            }
        }) { (error) in
        }
    }
}
