//
//  HistoryDailyMissonProtocols.swift
//  EnglishApp
//
//  Created Steve on 7/19/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HistoryDailyMissonWireframeProtocol: class {

}
//MARK: Presenter -
protocol HistoryDailyMissonPresenterProtocol: class {

    var interactor: HistoryDailyMissonInteractorInputProtocol? { get set }
    var listResultDailyMisson: [LessonCatelogy]? {get set}
    func getHistoryExercise(type: Int,date: String,offset: Int)
}

//MARK: Interactor -
protocol HistoryDailyMissonInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func getListLessonSuccessed(listLesson: [LessonCatelogy])
}

protocol HistoryDailyMissonInteractorInputProtocol: class {

    var presenter: HistoryDailyMissonInteractorOutputProtocol?  { get set }
    
    func getHistoryExercise(type: Int,date: String,offset: Int)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol HistoryDailyMissonViewProtocol: class {

    var presenter: HistoryDailyMissonPresenterProtocol?  { get set }
    func reloadView()

    /* Presenter -> ViewController */
}
