//
//  HistoryDailyMissonInteractor.swift
//  EnglishApp
//
//  Created Steve on 7/19/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryDailyMissonInteractor: HistoryDailyMissonInteractorInputProtocol {

    weak var presenter: HistoryDailyMissonInteractorOutputProtocol?
    
    func getTaskEveryDate(date: String,offset: Int) {
        ProgressView.shared.show()
        Provider.shared.exerciseAPIService.getTestResult(date: date, offset: offset, success: { (respone) in
            ProgressView.shared.hide()
            if let _respone = respone {
                self.presenter?.getListLessonSuccessed(listLesson: _respone.self_created_test?.compactMap{LessonCatelogy(selfCreatedTestEntity: $0)} ?? [])
            }
        }) { (error) in
            ProgressView.shared.hide()
        }
    }
}
