//
//  CommentInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/18/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CommentInteractor: CommentInteractorInputProtocol {

    weak var presenter: CommentInteractorOutputProtocol?
}
