//
//  CommentPresenter.swift
//  EnglishApp
//
//  Created vinova on 5/18/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class CommentPresenter: CommentPresenterProtocol, CommentInteractorOutputProtocol {

    weak private var view: CommentViewProtocol?
    var interactor: CommentInteractorInputProtocol?
    private let router: CommentWireframeProtocol

    init(interface: CommentViewProtocol, interactor: CommentInteractorInputProtocol?, router: CommentWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
