//
//  ExplainExerciseRouter.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExplainExerciseRouter: ExplainExerciseWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ExplainExerciseViewController(nibName: nil, bundle: nil)
        let interactor = ExplainExerciseInteractor()
        let router = ExplainExerciseRouter()
        let presenter = ExplainExercisePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    static func createModule(id: Int) -> ExplainExerciseViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ExplainExerciseViewController(nibName: nil, bundle: nil)
        view.id = id
        let interactor = ExplainExerciseInteractor()
        let router = ExplainExerciseRouter()
        let presenter = ExplainExercisePresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
