//
//  ExplainExerciseViewController.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip
import WebKit

class ExplainExerciseViewController: BaseViewController {

	var presenter: ExplainExercisePresenterProtocol?
    
    @IBOutlet weak var tvContent: TextViewHandleTap!
    var id: Int = 0
    
    override func setUpViews() {
        super.setUpViews()
        self.presenter?.getExplainQuestion(id: id)
        tvContent.callbackDoubleTap = {[weak self] (point, word) in
            guard let self = self else { return }
            let newPoint = self.tvContent.convert(point, to: self.view)
            self.presenter?.searchVocabulary(word: word, position: newPoint)
        }
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.explain_question.showLanguage)
    }
}
extension ExplainExerciseViewController : ExplainExerciseViewProtocol {
    
    func searchVocabularySuccessed(wordEntity: WordExplainEntity, position: CGPoint) {
        self.showPopoverVocabulary(x: position.x, y: position.y, size: CGSize.zero, word: wordEntity)
    }
    
    func reloadView() {
        if let explain = self.presenter?.explainQuestion?.explain {
            hideNoData()
            tvContent.attributedText = explain.html2Attributed
        } else {
            showNoData()
        }
    }
}
extension ExplainExerciseViewController : IndicatorInfoProvider {
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.explain_solution.showLanguage)
    }
}
