//
//  ExplainExerciseViewController.swift
//  EnglishApp
//
//  Created Steve on 7/28/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class ExplainExerciseViewController: BaseViewController {

	var presenter: ExplainExercisePresenterProtocol?

    @IBOutlet weak var lblExplainQuestion: UILabel!
    
    var id: Int = 0
    
    override func setUpViews() {
        super.setUpViews()
        self.presenter?.getExplainQuestion(id: id)
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        addBackToNavigation()
        setTitleNavigation(title: LocalizableKey.explain_question.showLanguage)
    }
}
extension ExplainExerciseViewController : ExplainExerciseViewProtocol {
    func reloadView() {
        if let explain = self.presenter?.explainQuestion?.explain {
            hideNoData()
            lblExplainQuestion.attributedText = explain.htmlToAttributedString
        } else {
            showNoData()
        }
    }
}
extension ExplainExerciseViewController : IndicatorInfoProvider {
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.explain_solution.showLanguage)
    }
}
