//
//  ExerciseInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/21/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExerciseInteractor: ExerciseInteractorInputProtocol {

    weak var presenter: ExerciseInteractorOutputProtocol?
}
