//
//  ExerciseRouter.swift
//  EnglishApp
//
//  Created vinova on 5/21/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExerciseRouter: ExerciseWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ExerciseViewController(nibName: nil, bundle: nil)
        let interactor = ExerciseInteractor()
        let router = ExerciseRouter()
        let presenter = ExercisePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    func gotoCreateExercise(){
        let vc = CreateExerciseRouter.createModule()
        self.viewController?.push(controller: vc,animated: true)
    }
    func gotoLevelExercise(){
        let vc = LevelExerciseRouter.createModule()
        self.viewController?.push(controller: vc,animated: true)
    }
}
