//
//  ExerciseViewController.swift
//  EnglishApp
//
//  Created vinova on 5/21/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ExerciseViewController: BaseViewController, ExerciseViewProtocol {

	var presenter: ExercisePresenterProtocol?
    
    @IBAction func clickCreateExercise(_ sender: Any) {
    }
    @IBAction func clickPracticeExercise(_ sender: Any) {
    }
    @IBAction func clickLevelExercise(_ sender: Any) {
    }
    @IBAction func clickAssignExercise(_ sender: Any) {
    }
    
    
    @IBOutlet weak var lbAssignExercise: UILabel!
    @IBOutlet weak var lbLevelExercise: UILabel!
    @IBOutlet weak var lbPracticeExercise: UILabel!
    @IBOutlet weak var lbCreateExercise: UILabel!
    @IBOutlet weak var vPracticeExercise: ViewGradient!
    @IBOutlet weak var vCreateExercise: ViewGradient!
    @IBOutlet weak var vLevelExercise: ViewGradient!
    @IBOutlet weak var vAssignExercise: ViewGradient!
    
    override func setUpViews() {
        super.setUpViews()
        
        vCreateExercise.setupGradient(beginColor: #colorLiteral(red: 0.7254902124, green: 0.4784313738, blue: 0.09803921729, alpha: 1), endColor: #colorLiteral(red: 0.7254902124, green: 0.4784313738, blue: 0.09803921729, alpha: 1))
        vPracticeExercise.setupGradient(beginColor: #colorLiteral(red: 0.3098039216, green: 0.6745098039, blue: 0.9960784314, alpha: 1), endColor: #colorLiteral(red: 0.3098039216, green: 0.6745098039, blue: 0.9960784314, alpha: 1))
        vLevelExercise.setupGradient(beginColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.7254901961, alpha: 1), endColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.7254901961, alpha: 1))
        vAssignExercise.setupGradient(beginColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.7254901961, alpha: 1), endColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.7254901961, alpha: 1))
        
        lbCreateExercise.text = LocalizableKey.create_exercise.showLanguage
        lbPracticeExercise.text = LocalizableKey.practice.showLanguage
         lbLevelExercise.text = LocalizableKey.level_exercise.showLanguage
        lbAssignExercise.text = LocalizableKey.assign_exercise.showLanguage
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        setTitleNavigation(title: LocalizableKey.exercise.showLanguage)
    }
    

}
