//
//  ExerciseViewController.swift
//  EnglishApp
//
//  Created vinova on 5/21/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class ExerciseViewController: BaseViewController, ExerciseViewProtocol {

	var presenter: ExercisePresenterProtocol?
    
    @IBAction func clickCreateExercise(_ sender: Any) {
        self.presenter?.gotoCreateExercise()
    }
    
    @IBAction func clickPracticeExercise(_ sender: Any) {
        self.presenter?.gotoPracticeExercise()
    }
    
    @IBAction func clickLevelExercise(_ sender: Any) {
        self.presenter?.gotoLevelExercise()
    }
    
    @IBAction func clickAssignExercise(_ sender: Any) {
        self.presenter?.gotoAssignExercise()
    }
    
    var isShowTabbar = true
    
    
    @IBOutlet weak var lbAssignExercise: UILabel!
    @IBOutlet weak var lbLevelExercise: UILabel!
    @IBOutlet weak var lbPracticeExercise: UILabel!
    @IBOutlet weak var lbCreateExercise: UILabel!
    @IBOutlet weak var vPracticeExercise: ViewGradient!
    @IBOutlet weak var vCreateExercise: ViewGradient!
    @IBOutlet weak var vLevelExercise: ViewGradient!
    @IBOutlet weak var vAssignExercise: ViewGradient!
    
    override func setUpViews() {
        super.setUpViews()
        
        vCreateExercise.setupGradient(beginColor: #colorLiteral(red: 1, green: 0.8274509804, blue: 0.06666666667, alpha: 1), endColor: #colorLiteral(red: 1, green: 0.8274509804, blue: 0.06666666667, alpha: 0.56))
        vPracticeExercise.setupGradient(beginColor: #colorLiteral(red: 0.3098039216, green: 0.6745098039, blue: 0.9960784314, alpha: 1), endColor: #colorLiteral(red: 0, green: 0.9490196078, blue: 0.9960784314, alpha: 1))
        vLevelExercise.setupGradient(beginColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.3333333333, alpha: 1), endColor: #colorLiteral(red: 0.1254901961, green: 0.7490196078, blue: 0.3333333333, alpha: 0.56))
        vAssignExercise.setupGradient(beginColor: #colorLiteral(red: 0.1725490196, green: 0.8549019608, blue: 0.8117647059, alpha: 1), endColor: #colorLiteral(red: 0.1725490196, green: 0.8549019608, blue: 0.8117647059, alpha: 0.56))
        
        lbCreateExercise.text = LocalizableKey.create_exercise.showLanguage
        lbPracticeExercise.text = LocalizableKey.practice.showLanguage
         lbLevelExercise.text = LocalizableKey.level_exercise.showLanguage
        lbAssignExercise.text = LocalizableKey.assign_exercise.showLanguage
    }
    
    override func viewWillAppear(_ animated: Bool) {
        if isShowTabbar {
            self.tabBarController?.tabBar.isHidden = false
        }
    }
    
    override func setUpNavigation() {
        super.setUpNavigation()
        setTitleNavigation(title: LocalizableKey.exercise.showLanguage)
    }
}

extension ExerciseViewController: IndicatorInfoProvider{
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return IndicatorInfo(title: LocalizableKey.exercise.showLanguage)
    }
}
