//
//  RelatedGrammarPresenter.swift
//  EnglishApp
//
//  Created Steve on 7/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RelatedGrammarPresenter: RelatedGrammarPresenterProtocol, RelatedGrammarInteractorOutputProtocol {

    weak private var view: RelatedGrammarViewProtocol?
    var interactor: RelatedGrammarInteractorInputProtocol?
    private let router: RelatedGrammarWireframeProtocol
    var isLoadmore = true
    var relatedLesson : RelatedLessonResponse?

    init(interface: RelatedGrammarViewProtocol, interactor: RelatedGrammarInteractorInputProtocol?, router: RelatedGrammarWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getListRelatedLesson(id: Int, offset: Int) {
        if isLoadmore {
            self.interactor?.getListRelatedLesson(id: id, offset: offset)
        }
    }
    func getListRelatedLessonSuccessed(response: RelatedLessonResponse) {
        if response.data.count < limit {
            isLoadmore = false
        }
        if relatedLesson == nil {
            self.relatedLesson = response
        } else {
            self.relatedLesson?.data += response.data
        }
        self.view?.reloadView()
    }

}
