//
//  RelatedGrammarRouter.swift
//  EnglishApp
//
//  Created Steve on 7/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RelatedGrammarRouter: RelatedGrammarWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RelatedGrammarViewController(nibName: nil, bundle: nil)
        let interactor = RelatedGrammarInteractor()
        let router = RelatedGrammarRouter()
        let presenter = RelatedGrammarPresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
    
    static func createModule(id: Int) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = RelatedGrammarViewController(nibName: nil, bundle: nil)
        view.id = id
        let interactor = RelatedGrammarInteractor()
        let router = RelatedGrammarRouter()
        let presenter = RelatedGrammarPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
