//
//  RelatedGrammarViewController.swift
//  EnglishApp
//
//  Created Steve on 7/29/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class RelatedGrammarViewController: ListManagerVC {

    var presenter: RelatedGrammarPresenterProtocol?
    var id: Int = 0

    override func viewDidLoad() {
        customTitle = LocalizableKey.related_lesson.showLanguage
        showButtonBack = true
        super.viewDidLoad()
    }
    
    override func registerTableView() {
        super.registerTableView()
        tableView.registerXibFile(CellGrammar.self)
    }
    
    override func callAPI() {
        super.callAPI()
        self.presenter?.getListRelatedLesson(id: id, offset: self.offset)
    }
    
    override func cellForRowListManager(item: Any, _ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let data = item as! SearchEntity
        let cell = tableView.dequeue(CellGrammar.self, for: indexPath)
        cell.setupTitle(title: data.name&)
        return cell
    }
    
    override func didSelectTableView(item: Any, indexPath: IndexPath) {
        let data = item as! SearchEntity
        let vc = DetailLessonRouter.createModule(idLesson: data._id  ?? "0")
        self.push(controller: vc)
    }
}

extension RelatedGrammarViewController : RelatedGrammarViewProtocol {
    func reloadView(listData: [SearchEntity]) {
        initLoadData(data: listData)
    }
}
