//
//  HistoryExerciseInteractor.swift
//  EnglishApp
//
//  Created vinova on 5/30/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryExerciseInteractor: HistoryExerciseInteractorInputProtocol {

    weak var presenter: HistoryExerciseInteractorOutputProtocol?
}
