//
//  TheoryViewController.swift
//  EnglishApp
//
//  Created vinova on 5/17/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import XLPagerTabStrip

class TheoryViewController: PageViewController, TheoryViewProtocol {

	var presenter: TheoryPresenterProtocol?

	override func viewDidLoad() {
        super.viewDidLoad()
        
        setTitleNavigation(title: LocalizableKey.theory.showLanguage)
        addButtonImageToNavigation(image: #imageLiteral(resourceName: "Material_Icons_white_search"), style: .right, action: #selector(clickButtonSearch))
    }
    
    @objc func clickButtonSearch(){
        self.presenter?.gotoSearchTheory()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(true)
        self.tabBarController?.tabBar.isHidden = false
        self.edgesForExtendedLayout = UIRectEdge.bottom
        self.view.window?.isHidden = true
    }
    
    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        return [LessonRouter.createModule(),LessonRouter.createModule(type: .recipe)]
    }
}
