//
//  HistoryCompetitionPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 6/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryCompetitionPresenter: HistoryCompetitionPresenterProtocol, HistoryCompetitionInteractorOutputProtocol {

    weak private var view: HistoryCompetitionViewProtocol?
    var interactor: HistoryCompetitionInteractorInputProtocol?
    private let router: HistoryCompetitionWireframeProtocol

    init(interface: HistoryCompetitionViewProtocol, interactor: HistoryCompetitionInteractorInputProtocol?, router: HistoryCompetitionWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}
