//
//  HistoryCompetitionInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 6/3/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HistoryCompetitionInteractor: HistoryCompetitionInteractorInputProtocol {

    weak var presenter: HistoryCompetitionInteractorOutputProtocol?
}
