//
//  ChangeLanguageRouter.swift
//  EnglishApp
//
//  Created Kai Pham on 6/2/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChangeLanguageRouter: ChangeLanguageWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> ChangeLanguageViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ChangeLanguageViewController.initFromNib()
        let interactor = ChangeLanguageInteractor()
        let router = ChangeLanguageRouter()
        let presenter = ChangeLanguagePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
