//
//  ChoiceExerciseRouter.swift
//  EnglishApp
//
//  Created vinova on 5/22/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ChoiceExerciseRouter: ChoiceExerciseWireframeProtocol {

    weak var viewController: UIViewController?

    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ChoiceExerciseViewController(nibName: nil, bundle: nil)
        let interactor = ChoiceExerciseInteractor()
        let router = ChoiceExerciseRouter()
        let presenter = ChoiceExercisePresenter(interface: view, interactor: interactor, router: router)

        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view

        return view
    }
}
