//
//  FindInteractor.swift
//  EnglishApp
//
//  Created Kai Pham on 6/8/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FindInteractor: FindInteractorInputProtocol {
 
    weak var presenter: FindInteractorOutputProtocol?
    
    func searchExercise(text: String) {
        ProgressView.shared.show()
        Provider.shared.findAPIService.searchExercise(text: text, success: { (respone) in
            ProgressView.shared.hide()
            self.presenter?.searchExerciseSuccessed(respone: respone)
        }) { (error) in
            ProgressView.shared.hide()
            if let _error = error {
//               self.presenter?.searchExerciseFailed(error: _error)
            }
            
        }
    }
    
    func searchTheory(text: String){
        Provider.shared.findAPIService.searchTheory(text: text, success: { (respone) in
            ProgressView.shared.hide()
            self.presenter?.searchTheorySuccessed(respone: respone)
        }) { (error) in
            ProgressView.shared.hide()
            if let _error = error {
//                self.presenter?.searchExerciseFailed(error: _error)
            }
            
        }
    }
}
