//
//  FindPresenter.swift
//  EnglishApp
//
//  Created Kai Pham on 6/8/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class FindPresenter: FindPresenterProtocol, FindInteractorOutputProtocol {
    
    weak private var view: FindViewProtocol?
    var interactor: FindInteractorInputProtocol?
    private let router: FindWireframeProtocol
    var searchRespone : [SearchEntity] = []
    var error: APIError?

    init(interface: FindViewProtocol, interactor: FindInteractorInputProtocol?, router: FindWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
    
    func getMessageError() -> String? {
        return error?.message
    }
    
    func getNumberSearch() -> Int {
        return searchRespone.count
    }
    
    func getTextSearch(indexPath: IndexPath) -> String? {
        return searchRespone[indexPath.row].name
    }
    
    
    func searchExercise(text: String) {
        self.interactor?.searchExercise(text: text)
    }
    
    func searchTheory(text: String){
        self.interactor?.searchTheory(text: text)
    }
    
    func getIdEntity(indexPath: IndexPath) -> String?{
        return searchRespone[indexPath.row]._id
    }
    
    func searchExerciseSuccessed(respone: [SearchEntity]) {
        searchRespone = respone
        self.view?.reloadView()
    }
    
    func searchExerciseFailed(error: APIError) {
        self.error = error
        self.view?.showErrorSearchFailed()
    }
    
    func gotoTheoryDetail(idLesson: String){
        self.router.gotoTheoryDetail(idLesson: idLesson)
    }
}
