//
//  FindProtocols.swift
//  EnglishApp
//
//  Created Kai Pham on 6/8/19.
//  Copyright © 2019 demo. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol FindWireframeProtocol: class {

}
//MARK: Presenter -
protocol FindPresenterProtocol: class {

    var interactor: FindInteractorInputProtocol? { get set }
    func searchExercise(text: String)
    func getMessageError() -> String?
    func getTextSearch(indexPath: IndexPath) -> String?
    func getNumberSearch() -> Int
}

//MARK: Interactor -
protocol FindInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
    func searchExerciseSuccessed(respone: [SearchEntity])
    func searchExerciseFailed(error: APIError)
}

protocol FindInteractorInputProtocol: class {

    var presenter: FindInteractorOutputProtocol?  { get set }
    func searchExercise(text: String)

    /* Presenter -> Interactor */
}

//MARK: View -
protocol FindViewProtocol: class {

    var presenter: FindPresenterProtocol?  { get set }
    func reloadView()
    func showErrorSearchFailed()

    /* Presenter -> ViewController */
}
